version: '3.8'

services:
  web:
    build: .
    ports:
      - "5050:5050"
    environment:
      - FLASK_ENV=development & celery worker -A app.subscribe.task --loglevel=DEBUG & celery -A make_celery beat --loglevel DEBUG
      - FLASK_APP=app

  test:
    build: .
    command: pytest
    depends_on:
      - web

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"