version: '3.8'

services:
  web:
    build: .
    ports:
      - "5050:5050"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app

  test:
    build: .
    command: pytest
    depends_on:
      - web

  redis:
    image: "redis:latest"